version: "3.1"

services:
  nodejs:
    container_name: api-blog
    restart: always
    build: .
    ports:
      - 3000:3000
    links:
      - mongo
    volumes:
      - .:/usr/src/app

  mongo:
    container_name: db-api-blog
    image: mongo:6
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: api-blog
    volumes:
      - ./data:/data/db
      - ./data/log:/var/log/mongodb/
    logging:
      driver: none

  mongo-express:
    image: mongo-express
    container_name: mongo-expres
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    logging:
      driver: none
